### ISSUE TITLE
Ripper projectile unrealscript crash (Razor2.SetRoll not found)

### ISSUE THREAD

**Issue by Xaleros** [dpjudas/UTEngine#20]
Shooting ripper blades has a chance to crash the game after it hits a wall. Needs further investigation but my initial theory is this:

- Ripper projectile (class Razor2) spawns, starting in state 'Flying'
- eventually leaves state 'Flying' (maybe when it gets destroyed?)
- tries to call SetRoll again somehow, which is only in `state Flying`, crash

**Comment by Xaleros** [comment]
Seems like UActor::Destroy() was changing actor state to a None state when it shouldn't have been. Fixed on my repo

**Comment by dpjudas** [comment]
I applied this fix. Hopefully it won't have any side effects. I guess we'll see in time. Thanks for the help tracing it down. :)
