### ISSUE TITLE
LevelInfo.GetAddressURL not implemented error

### ISSUE THREAD

**Issue by rohit-n** [dpjudas/UTEngine#3]
```
Unhandled exception: Script execution error:

LevelInfo.GetAddressURL not implemented

Call stack:

GameInfo.GetServerPort line 365
StatLogFile.StartLog line 32
GameInfo.InitLogging line 218
GameInfo.PostBeginPlay line 183
DeathMatchPlus.PostBeginPlay line 85

```

**Comment by dpjudas** [comment]
There are a lot of those. Don't expect the thing to be fully playable anytime soon. For example, inventory, travel and physics are completely unimplemented right now.

Currently I'm working on the crashes when starting a game or opening the preferences menu. I don't need bug reports on them at this stage. :)

**Comment by rohit-n** [comment]
I'm aware, but I was able to load a level a few commits ago, so I wanted to make sure this error wasn't an unintentional regression.

Thanks for your work on this project.

**Comment by dpjudas** [comment]
What it could load probably regressed when I pushed the code that actually spawns the player pawns and ticks the level actors.  That push also broke the skyzone rendering.

Which map are you seeing this error on? If it's CTF-EternalCaves that I'm currently testing with then there's something wrong. If it is some other map then it is probably expected right now.

**Comment by rohit-n** [comment]
Yes, CTF-EternalCave is showing that error.

**Comment by dpjudas** [comment]
That's interesting! There must be some difference between your UnrealTournament.ini + User.ini files and the ones I am using. At least that's the only theory I have for this. I don't think it's a Linux vs Windows issue or anything like that.

**Comment by rohit-n** [comment]
Latest commit fixes the error, thanks! Closing this issue.
