### ISSUE TITLE
Patreon or other sponsership

### ISSUE THREAD

**Issue by MindrustUK** [dpjudas/UTEngine#4]
Hi @dpjudas do you have a Patreon or other ways of supporting your work on the UTEngine project?

**Comment by dpjudas** [comment]
Thanks for offering financial support! I do not have a Patreon and I think it is better for the project if there's no financial ties to it.

I'm not sure how Epic will react to this project if I actually get it to run the game. I'd really prefer if Tim Sweeney approves of what I've been doing here. To maximize the chance of that it must be a strict hobby project.

**Comment by MindrustUK** [comment]
Ah, I understand. Well thanks for this work and best of luck! Unreal is possibly one of the best games I've ever played and I'm hoping this will allow it to live on for a long time.

**Comment by eukara** [comment]
Just want to thank you for this as well. I built it today on amd64-linux and I was in awe of how much worked already. Very impressive and a true achievement. No one can take this away from you!
